run:
  timeout: 2m
  issues-exit-code: 1
  modules-download-mode: readonly
  format: line-number,stderr

linters-settings:
  cyclop:
    max-complexity: 10
    package-average: 5
    skip-tests: false
  depguard:
    rules:
      main:
        files:
          - $all
        deny:
          - pkg: reflect
            desc: "avoid reflect"
      test:
        files:
          - $all
        deny:
          - pkg: reflect
            desc: "avoid reflect"
  errcheck:
    check-type-assertions: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  govet:
    check-shadowing: true
  nolintlint:
    require-explanation: true
    require-specific: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - cyclop
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - nakedret
    - prealloc
    - predeclared
    - staticcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
